image: my-cf-lugin
tag: "34"
version: "34"
categories: ["Security"]
description: Codefresh Plugin
keywords: ['docker']
sources: []
maintainers:
- name: Your Name
  email: Your Email
icon: ""
envs: []
